version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/var/www/html  # Mount the current directory to the container
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=project_db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data

volumes:
  db_data: